# Generated by Django 3.2.8 on 2021-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
