# Generated by Django 4.0 on 2022-01-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0004_userlogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=1, upload_to='images/nature'),
            preserve_default=False,
        ),
    ]
